import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Menu } from "@/components/Menu";
import Provider from "@/services/Providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={(inter.className, "bg-slate-50 text-slate-950 w-screen h-screen")}>
        <Provider>
          <Menu />
          {children}
        </Provider>
      </body>
    </html>
  );
}
